### ISSUE TITLE
Can you provide a preview of this module? 

### ISSUE THREAD

**Issue by riccardogiorato** [Dante83/SkyForge#1]
Can you provide a preview of this module? You could use netlify it lets you easily synch github repositories with a free web hosting.

[Netlify](http://netlify.com/)

Or at least provide some screenshot of this module at work, if you want I might help to do those things if you add me as collaborator, does it sounds good?
And I could update the README too.

**Comment by Dante83** [comment]
Oops! Sorry, I had it linked on the A-Frame projects page and on my page but not on here yet.

http://code-panda.com/pages/projects/a_sky_forge_example

That should do the trick though. I should say that it's a bit heavy on the GPU usage. I still need to find out how to better remedy that, but my efforts toying around with the GLSL just haven't proven useful (I'm still such a noob to GLSL). I'll add the link on the page next time I push an update.

Also, as of the time of this writing, we're currently a couple of days from a new moon, so it should be fairly hard to see. But it's there! I've checked. *Right near the sun as a dark disk.

**Comment by Dante83** [comment]
Ok, I've added this into the README.md file. So I'm going to close out this issue. Thiank you so much for your feedback ^_^.
