### ISSUE TITLE
Does not work with oculus quest 

### ISSUE THREAD

**Issue by justAnormalUser00** [Dante83/SkyForge#4]
I tried http://code-panda.com/pages/projects/v_0_3_0/a_sky_forge_lunar_eclipse_example this in oculus quest native browser and firefox.
result >> grayisch sky, really laggy
 I guess the issue is memory/performance related.. on my desktop(firefox) it works well.

**Comment by Dante83** [comment]
That's a high likelihood. Are you in tethered or untethered mode? Having additional power often allows mobile devices to switch to higher graphics settings that are normally unavailable at lower settings to reduce the power load.

I've noticed that the sky tends to lag on my macbook air, but works well on my RX580 machine (It was developed using a GTX 1070). I do not have a Quest to verify this with, however. I believe most of the computational cost comes from the extensive computational load that the sky puts on the GPU. V 0.3.0 (currently master) does a good job of improving performance, but it's still not a perfect solution. I'm working out an entire redo of the project, slated for V 1.0.0 in the future, but that's a ways off while I'm still figuring out the technology and waiting for some of it to mature. Even then, I'm uncertain if this will truly improve performance enough to bridge the gap. Thank you for giving it a shot, however.

**Comment by justAnormalUser00** [comment]
i tried tethered mode... same problem. The quest browser isn't that great a performance monitor is missing so i cant pinpoint the problem. However thanks for your help.
